# Reference: https://mdformat.readthedocs.io/en/stable/users/configuration_file.html
#
wrap = 79           # possible values: {"keep", "no", INTEGER}
number = false      # possible values: {false, true}
end_of_line = "lf"  # possible values: {"lf", "crlf"}
